Repository y-media/pinktube, pull requests merged in 2023-10, with the labels that each got.

#29 Feature/searchvideo
  .idea/vcs.xml
  app/src/main/java/com/example/spartube/main/MainViewPagerAdapter.kt
  app/src/main/java/com/example/spartube/search/SearchFragment.kt
  app/src/main/java/com/example/spartube/search/SearchPageAdapter.kt
  app/src/main/java/com/example/spartube/search/SearchPageEntity.kt
  app/src/main/res/drawable/ic_search_searchbutton.png
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/search_page_item.xml
Labels: feature

#30 [FEAT] : homefragment/CategoryChannelAdapter
  .idea/misc.xml
  app/build.gradle
  app/src/main/assets/animation_y_media.json
  app/src/main/java/com/example/spartube/home/HomeFragment.kt
  app/src/main/java/com/example/spartube/home/adapter/CategoryAdapter.kt
  app/src/main/java/com/example/spartube/home/adapter/CategoryChannelAdapter.kt
  app/src/main/java/com/example/spartube/home/adapter/HomeAdapter.kt
  app/src/main/res/drawable/ic_pink_tube1.xml
  app/src/main/res/drawable/ic_pink_tube2.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_recycler_home.xml
  app/src/main/res/layout/splash_screen.xml
  app/src/main/res/values/colors.xml
Labels: feature

#31 Feature/detailfragment
  app/src/main/java/com/example/spartube/detail/DetailPageFragment.kt
  app/src/main/res/anim/slide_down_enter.xml
  app/src/main/res/anim/slide_down_exit.xml
  app/src/main/res/layout/fragment_detail_page.xml
Labels: feature

#32 [FEAT] shorts 페이지 기능구현
  app/build.gradle
  app/src/main/java/com/example/spartube/data/model/commentmodel/AuthorChannelId.kt
  app/src/main/java/com/example/spartube/data/model/commentmodel/Comment.kt
  app/src/main/java/com/example/spartube/data/model/commentmodel/Item.kt
  app/src/main/java/com/example/spartube/data/model/commentmodel/PageInfo.kt
  app/src/main/java/com/example/spartube/data/model/commentmodel/Replies.kt
  app/src/main/java/com/example/spartube/data/model/commentmodel/ResponseComment.kt
  app/src/main/java/com/example/spartube/data/model/commentmodel/Snippet.kt
  app/src/main/java/com/example/spartube/data/model/commentmodel/SnippetX.kt
  app/src/main/java/com/example/spartube/data/model/commentmodel/SnippetXX.kt
  app/src/main/java/com/example/spartube/data/model/commentmodel/TopLevelComment.kt
  app/src/main/java/com/example/spartube/data/model/searchmodel/Default.kt
  app/src/main/java/com/example/spartube/data/model/searchmodel/High.kt
  app/src/main/java/com/example/spartube/data/model/searchmodel/Id.kt
  app/src/main/java/com/example/spartube/data/model/searchmodel/Item.kt
  app/src/main/java/com/example/spartube/data/model/searchmodel/Medium.kt
  app/src/main/java/com/example/spartube/data/model/searchmodel/PageInfo.kt
  app/src/main/java/com/example/spartube/data/model/searchmodel/ResponseSearch.kt
  app/src/main/java/com/example/spartube/data/model/searchmodel/Snippet.kt
  app/src/main/java/com/example/spartube/data/model/searchmodel/Thumbnails.kt
  app/src/main/java/com/example/spartube/data/service/RetrofitModule.kt
  app/src/main/java/com/example/spartube/data/service/YouTubeSearchService.kt
  app/src/main/java/com/example/spartube/db/MyPageDao.kt
  app/src/main/java/com/example/spartube/db/MyPageEntity.kt
  app/src/main/java/com/example/spartube/shorts/BottomSheetCommentFragment.kt
  app/src/main/java/com/example/spartube/shorts/ShortsPageFragment.kt
  app/src/main/java/com/example/spartube/shorts/listener/ShortsItemClickListener.kt
  app/src/main/java/com/example/spartube/shorts/recyclerviewutil/BindingModels.kt
  app/src/main/java/com/example/spartube/shorts/recyclerviewutil/CommentsAdapter.kt
  app/src/main/java/com/example/spartube/shorts/recyclerviewutil/CommentsViewHolder.kt
  app/src/main/java/com/example/spartube/shorts/recyclerviewutil/ShortsPageAdapter.kt
  app/src/main/java/com/example/spartube/shorts/recyclerviewutil/ShortsViewHolder.kt
  app/src/main/java/com/example/spartube/shorts/recyclerviewutil/reply/MainCommentViewHolder.kt
  app/src/main/java/com/example/spartube/shorts/recyclerviewutil/reply/ReplyAdapter.kt
  app/src/main/java/com/example/spartube/shorts/recyclerviewutil/reply/ReplyViewHolder.kt
  app/src/main/java/com/example/spartube/shorts/util/CustomPlayerUiController.kt
  app/src/main/java/com/example/spartube/shorts/util/SnapPagerScrollListener.kt
  app/src/main/java/com/example/spartube/util/Converter.kt
  app/src/main/res/drawable/bottom_sheet_round_background.xml
  app/src/main/res/drawable/ic_arrow_back.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_comment.xml
  app/src/main/res/drawable/ic_heart_empty.xml
  app/src/main/res/drawable/ic_heart_filled.xml
  app/src/main/res/drawable/ic_pause.xml
  app/src/main/res/drawable/ic_play.xml
  app/src/main/res/drawable/ic_share_btn.xml
  app/src/main/res/drawable/ic_thumbs_up.xml
  app/src/main/res/drawable/selector_is_liked.xml
  app/src/main/res/layout/fragment_shorts_page.xml
  app/src/main/res/layout/shorts_comment.xml
  app/src/main/res/layout/shorts_custom_view.xml
  app/src/main/res/layout/shorts_page_comment_item.xml
  app/src/main/res/layout/shorts_page_item.xml
  app/src/main/res/layout/shorts_page_replyitem.xml
  app/src/main/res/values/strings.xml
Labels: feature, design

#38 [Feature, Design]detail page fragment
  app/build.gradle
  app/src/main/java/com/example/spartube/detail/DetailPageFragment.kt
  app/src/main/java/com/example/spartube/home/HomeFragment.kt
  app/src/main/java/com/example/spartube/home/adapter/HomeAdapter.kt
  app/src/main/java/com/example/spartube/shorts/recyclerviewutil/CommentsViewHolder.kt
  app/src/main/java/com/example/spartube/shorts/recyclerviewutil/reply/MainCommentViewHolder.kt
  app/src/main/java/com/example/spartube/shorts/recyclerviewutil/reply/ReplyViewHolder.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_detail_page.xml
Labels: feature, design

#40 [Feature]detailfragment
  app/src/main/java/com/example/spartube/SplashScreen.kt
  app/src/main/java/com/example/spartube/detail/DetailPageFragment.kt
  app/src/main/java/com/example/spartube/home/HomeFragment.kt
  app/src/main/java/com/example/spartube/home/adapter/CategoryAdapter.kt
  app/src/main/java/com/example/spartube/home/adapter/HomeAdapter.kt
  app/src/main/res/anim/slide_up_enter.xml
  app/src/main/res/layout/fragment_detail_page.xml
Labels: feature, design

#41 [FEAT] : ⚙️(sd): 검색해서 썸네일이랑 타이틀 표시기능
  app/src/main/java/com/example/spartube/data/service/RetrofitModule.kt
  app/src/main/java/com/example/spartube/data/service/YouTubeSearchService.kt
  app/src/main/java/com/example/spartube/search/SearchFragment.kt
  app/src/main/java/com/example/spartube/search/SearchPageAdapter.kt
  app/src/main/java/com/example/spartube/search/SearchPageEntity.kt
  app/src/main/res/layout/search_page_item.xml
Labels: feature

#45 [FEAT] 데이터베이스 연결, 데이터 없을시 보여줄 화면 완성
  app/src/main/java/com/example/spartube/db/AppDatabase.kt
  app/src/main/java/com/example/spartube/db/MyPageDao.kt
  app/src/main/java/com/example/spartube/detail/DetailPageFragment.kt
  app/src/main/java/com/example/spartube/home/HomeFragment.kt
  app/src/main/java/com/example/spartube/mypage/MyPageAdapter.kt
  app/src/main/java/com/example/spartube/mypage/MyPageFragment.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: feature

#46 [Feature]reply detail page
  app/src/main/java/com/example/spartube/data/service/YouTubeSearchService.kt
  app/src/main/java/com/example/spartube/detail/DetailPageFragment.kt
  app/src/main/res/layout/fragment_detail_page.xml
Labels: bug, feature, design

#48 [FEAT] : ⚙️검색 했을때 나오는 나오는 화면 클릭시 detailpage로 이동
  app/src/main/java/com/example/spartube/detail/DetailPageFragment.kt
  app/src/main/java/com/example/spartube/search/SearchFragment.kt
  app/src/main/java/com/example/spartube/search/SearchPageAdapter.kt
  app/src/main/java/com/example/spartube/search/SearchPageEntity.kt
Labels: feature

#49 [FEAT] 디테일페이지 및 쇼츠페이지에서 좋아요를 누르면 마이페이지에 해당 영상 목록 띄우주게 만들기
  app/src/main/java/com/example/spartube/detail/DetailPageFragment.kt
  app/src/main/java/com/example/spartube/mypage/MyPageAdapter.kt
  app/src/main/java/com/example/spartube/mypage/MyPageFragment.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: feature

#51 [FEAT] 데이터가 있을시 데이터만 나오고, 없을시 아무것도 없다는 이미지와 텍스트 출력
  app/src/main/java/com/example/spartube/mypage/MyPageFragment.kt
Labels: feature

#55 [Feature]minor modify
  .idea/deploymentTargetDropDown.xml
  app/src/main/res/layout/fragment_detail_page.xml
Labels: design

#56 [RENAME] comment 파일 패키지 분리
  app/src/main/java/com/example/spartube/comment/BottomSheetCommentFragment.kt
  app/src/main/java/com/example/spartube/comment/CommentsAdapter.kt
  app/src/main/java/com/example/spartube/comment/CommentsViewHolder.kt
  app/src/main/java/com/example/spartube/comment/reply/MainCommentViewHolder.kt
  app/src/main/java/com/example/spartube/comment/reply/ReplyAdapter.kt
  app/src/main/java/com/example/spartube/comment/reply/ReplyViewHolder.kt
  app/src/main/java/com/example/spartube/detail/DetailPageFragment.kt
  app/src/main/java/com/example/spartube/shorts/ShortsPageFragment.kt
  app/src/main/java/com/example/spartube/shorts/adapter/BindingModels.kt
  app/src/main/java/com/example/spartube/shorts/adapter/ShortsPageAdapter.kt
  app/src/main/java/com/example/spartube/shorts/adapter/ShortsViewHolder.kt
Labels: documentation

#59 [FEAT] 앱 실행 중 인터넷 연결 감지
  app/build.gradle
  app/src/main/java/com/example/spartube/main/MainActivity.kt
  app/src/main/java/com/example/spartube/main/MainViewModel.kt
  app/src/main/java/com/example/spartube/util/ConnectWatcher.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
Labels: feature

#60 [FEAT] 디테일페이지 좋아요 기능 구현 완료, 마이페이지 와 연동 완료 및 서치페이지 url 전달 코드 추가
  app/src/main/java/com/example/spartube/detail/DetailPageFragment.kt
  app/src/main/java/com/example/spartube/mypage/MyPageFragment.kt
  app/src/main/java/com/example/spartube/search/SearchFragment.kt
  app/src/main/res/drawable/dark_flame.png
  app/src/main/res/layout/fragment_detail_page.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: feature

#61 [DESIGN]searchfragment UI수정
  app/src/main/java/com/example/spartube/search/SearchFragment.kt
  app/src/main/res/drawable/edittext_search_roundconer.xml
  app/src/main/res/drawable/ic_search_searchbutton.png
  app/src/main/res/drawable/ic_search_searchbutton2.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/search_page_item.xml
Labels: design

#62 [Design]minor modifying
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_recycler_home.xml
Labels: documentation, design

#64 [FIX] 홈프레그먼트에서 디테일로 url 보내주는 코드 추가, 마이페이지 xml 프로필 추가, 디테일페이지 좋아요 기능 수정
  app/src/main/java/com/example/spartube/detail/DetailPageFragment.kt
  app/src/main/java/com/example/spartube/home/HomeFragment.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: feature

#67 [DESIGN] : 🎨(sd): UI 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/search_page_item.xml
Labels: design

#69 [FIX] short - mypage 좋아요 동기화
  app/src/main/java/com/example/spartube/search/SearchPageAdapter.kt
  app/src/main/java/com/example/spartube/shorts/ShortsPageFragment.kt
  app/src/main/java/com/example/spartube/shorts/adapter/BindingModels.kt
  app/src/main/java/com/example/spartube/shorts/adapter/ShortsViewHolder.kt
Labels: bug
