Repository y-media/pinktube, pull requests merged in 2023-09, with the labels that each got.

#6 [DESIGN] : 🎨
  app/src/main/java/com/example/spartube/main/MainViewPagerAdapter.kt
  app/src/main/res/layout/fragment_shorts_page.xml
  app/src/main/res/layout/shorts_page_item.xml
Labels: ui

#7 [DESIGN] : 🎨
  .idea/.name
  app/src/main/java/com/example/spartube/main/MainViewPagerAdapter.kt
  app/src/main/res/drawable/ic_back_btn.xml
  app/src/main/res/drawable/ic_comment.xml
  app/src/main/res/drawable/ic_heart_empty.xml
  app/src/main/res/drawable/ic_heart_filled.xml
  app/src/main/res/drawable/ic_inbox.xml
  app/src/main/res/drawable/ic_profile.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_share_btn.xml
  app/src/main/res/drawable/img_loopy.png
  app/src/main/res/layout/fragment_detail_page.xml
Labels: ui

#9 [DESIGN] : 🎨
  app/build.gradle
  app/src/main/res/drawable/ic_loading_img.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_recycler_home.xml
  app/src/main/res/values/strings.xml
Labels: ui

#12 [FEAT] : ⚙️
  app/build.gradle
  app/src/main/java/com/example/spartube/db/AppDatabase.kt
  app/src/main/java/com/example/spartube/db/MyPageDao.kt
  app/src/main/java/com/example/spartube/db/MyPageEntity.kt
Labels: feature

#14 [FEAT] retrofit - youtube api 기본 세팅
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/assets/animation_y_media.json
  app/src/main/java/com/example/spartube/data/model/categorymodel/Item.kt
  app/src/main/java/com/example/spartube/data/model/categorymodel/ResponseCategory.kt
  app/src/main/java/com/example/spartube/data/model/categorymodel/Snippet.kt
  app/src/main/java/com/example/spartube/data/model/videomodel/ContentDetails.kt
  app/src/main/java/com/example/spartube/data/model/videomodel/ContentRating.kt
  app/src/main/java/com/example/spartube/data/model/videomodel/Default.kt
  app/src/main/java/com/example/spartube/data/model/videomodel/High.kt
  app/src/main/java/com/example/spartube/data/model/videomodel/Item.kt
  app/src/main/java/com/example/spartube/data/model/videomodel/Localized.kt
  app/src/main/java/com/example/spartube/data/model/videomodel/Maxres.kt
  app/src/main/java/com/example/spartube/data/model/videomodel/Medium.kt
  app/src/main/java/com/example/spartube/data/model/videomodel/PageInfo.kt
  app/src/main/java/com/example/spartube/data/model/videomodel/ResponseModel.kt
  app/src/main/java/com/example/spartube/data/model/videomodel/Snippet.kt
  app/src/main/java/com/example/spartube/data/model/videomodel/Standard.kt
  app/src/main/java/com/example/spartube/data/model/videomodel/Statistics.kt
  app/src/main/java/com/example/spartube/data/model/videomodel/Thumbnails.kt
  app/src/main/java/com/example/spartube/data/service/RetrofitModule.kt
  app/src/main/java/com/example/spartube/data/service/YouTubeSearchService.kt
  app/src/main/java/com/example/spartube/home/HomeFragment.kt
  app/src/main/java/com/example/spartube/home/adapter/CategoryAdapter.kt
  app/src/main/java/com/example/spartube/home/adapter/HomeAdapter.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_recycler_home.xml
  app/src/main/res/layout/splash_screen.xml
Labels: feature, design

#20 [FEAT] : homefragment/channel
  app/build.gradle
  app/src/main/java/com/example/spartube/home/HomeFragment.kt
  app/src/main/java/com/example/spartube/home/adapter/CategoryChannelAdapter.kt
  app/src/main/java/com/example/spartube/home/adapter/HomeAdapter.kt
  app/src/main/res/layout/fragment_home.xml
Labels: feature

#21 [FEAT] : ⚙️ 공유기능 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/spartube/detail/DetailPageFragment.kt
  app/src/main/res/layout/fragment_detail_page.xml
Labels: feature

#22 UI/search fragment
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/src/main/java/com/example/spartube/main/MainViewPagerAdapter.kt
  app/src/main/java/com/example/spartube/search/SearchFragment.kt
  app/src/main/res/drawable/edittext_search_roundconer.xml
  app/src/main/res/layout/fragment_search.xml
Labels: design

#23 [FEAT] MapageFragment, MypageAdapter 연
  .idea/deploymentTargetDropDown.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/spartube/main/MainActivity.kt
  app/src/main/java/com/example/spartube/main/MainViewPagerAdapter.kt
  app/src/main/java/com/example/spartube/mypage/MyPageAdapter.kt
  app/src/main/java/com/example/spartube/mypage/MyPageFragment.kt
  app/src/main/res/drawable/anime.png
  app/src/main/res/drawable/background.png
  app/src/main/res/drawable/bonobono.png
  app/src/main/res/drawable/lupi.png
  app/src/main/res/drawable/oni.png
  app/src/main/res/layout/fragment_my_page.xml
Labels: feature

#24 [FEAT] shorts 기능 구현 (ing)
  app/build.gradle
  app/src/main/java/com/example/spartube/data/service/RetrofitModule.kt
  app/src/main/java/com/example/spartube/data/service/YouTubeSearchService.kt
  app/src/main/java/com/example/spartube/shorts/ShortsPageAdapter.kt
  app/src/main/java/com/example/spartube/shorts/ShortsPageFragment.kt
  app/src/main/java/com/example/spartube/shorts/listener/ShortsItemClickListener.kt
  app/src/main/res/drawable/progressbar_style.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_shorts_page.xml
  app/src/main/res/layout/shorts_page_item.xml
Labels: feature

#28 [HOTFIX] 패키지 버그 등 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/spartube/main/MainViewPagerAdapter.kt
  app/src/main/java/com/example/spartube/mypage/MyPageAdapter.kt
  app/src/main/java/com/example/spartube/mypage/MyPageFragment.kt
  app/src/main/java/com/example/spartube/search/SearchFragment.kt
  app/src/main/res/layout/fragment_search.xml
Labels: bug
